version : '3'
services: 
    mongodb:
        image: mongo
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=password
        volumes:
            - mongo-data:/data/db  # /data/db is where mongodb physically store the data
    # my_todo:
    #     build: . #given context where Dockerfile is located
    #     ports:
    #         - 5000:5000
    #     depends_on:
    #         - mongodb

    mongo-express:
        image: mongo-express
        ports:
            - 8081:8081
        depends_on:
            - mongodb
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
            - ME_CONFIG_MONGODB_ADMINPASSWORD=password
            - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
    mongo-data:  #define named volume
        driver: local  #store on local (Docker storage)
